version: "3.8"

services:
  retail-mysql:
    image: mysql:8.4.4
    container_name: retail-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mysecure@123
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pMysecure@123"]
      interval: 10s
      timeout: 5s
      retries: 5

  retail-banking-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retail-banking-container
    ports:
      - "9090:8080"
    depends_on:
      retail-mysql:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql_data:
