apiVersion: v1
kind: Service
metadata:
  name: retail-mysql
spec:
  selector:
    app: retail-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Headless service (no load balancing)
