apiVersion: v1
kind: Service
metadata:
  name: retail-banking-service
spec:
  type: NodePort
  selector:
    app: retail-banking
  ports:
    - port: 9090
      targetPort: 8080
      nodePort: 30036
