name: Banking PR Builder

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Spin Database Container
      run: docker run -d --rm -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mariadb:10.3 --lower_case_table_names=1
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Cache Maven Dependecies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-  
    
    - name: Build with Maven
      run: mvn clean verify
      env:
        GCP_MYSQL_DB_HOST: 0.0.0.0
        GCP_MYSQL_DB_PORT: 3306
        GCP_MYSQL_DB_UNAME: root
        GCP_MYSQL_DB_PASSWD: root
